#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use \Symfony\Component\Console\Application;

$application = new Application();

// ... register commandsj
$application->add(new App\Console\Migrations());

$application->run();