version: "3"
services:
    web:
        build: 
            context: .
            dockerfile: web.Dockerfile
        ports:
            - "$HTTP_PORT_BACK:80"
        tty: 
            true
        networks:
            net:
        depends_on:
            - app
        volumes:
            - ../:/var/www/html
        restart: always
        container_name: len_web
    app:
        build: 
            context: ../
            dockerfile: docker/app.Dockerfile
        tty: 
            true
        environment:
            # Ключ приложения
            APP_KEY: $APP_KEY
            APP_ENV: $APP_ENV

        networks:
            net:
        volumes:
            - ../:/var/www/html
        restart: always
        container_name: len_app
    db:
        image: mysql:8.0
        ports:
            - "$DB_PORT:5432"
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
        networks:
            net:
        volumes:
           - ./storage/mysql:/var/lib/mysql
        restart: always
        container_name: len_db

networks:
    net:
        driver: bridge
        ipam:
            driver: default
            config:
                -
                    subnet: $NETWORK
